// VendeFrío - Catálogo de venta móvil
(function () {
    let catalogoCreado = false;
    function crear() {
        if (catalogoCreado) return document.getElementById("pantallaCatalogo");
        const s = document.createElement("section"); s.id = "pantallaCatalogo"; s.className = "oculto pantallaExtra pantallaCatalogo";
        s.innerHTML = `<header><div class="logo">🛍️</div><div><h1>Catálogo</h1><p>Productos y precios para vender</p></div></header><main class="container"><button class="extraVolver" type="button">‹ Volver</button><div class="catalogoFiltros"><input id="buscarCatalogo" class="buscadorCatalogo" type="search" placeholder="Buscar producto..."><select id="filtroMarcaCatalogo" aria-label="Filtrar por marca"><option value="todas">Todas las marcas</option></select></div><div id="grillaCatalogo" class="grillaCatalogo"></div></main></section>`;
        document.body.insertBefore(s, document.querySelector("nav.bottom-nav")); s.querySelector(".extraVolver").onclick = () => { s.classList.add("oculto"); mostrarPantalla("menu"); }; s.querySelector("#buscarCatalogo").oninput = renderizar; s.querySelector("#filtroMarcaCatalogo").onchange = renderizar; catalogoCreado = true; return s;
    }
    function datos() { const productos = typeof obtenerProductos === "function" ? obtenerProductos() : {}; const lista = []; Object.entries(productos).forEach(([marca, items]) => (items || []).forEach(item => { const p = typeof item === "string" ? { nombre: item } : item || {}; lista.push({ ...p, nombre: p.nombre || p.producto || "Producto", marca }); })); return lista; }
    function abrirEditorFoto(archivo, alGuardar) {
        const lector = new FileReader();
        lector.onload = () => {
            const imagen = new Image(); imagen.onload = () => {
                const modal = document.createElement("div"); modal.className = "modalCatalogo modalEditorFoto";
                modal.innerHTML = `<div class="modalCatalogoContenido editorFotoContenido"><div class="modalCatalogoTitulo"><strong>Ajustar foto</strong><button type="button" class="cerrarModalCatalogo">×</button></div><p class="subtitulo">Mové la imagen y ajustá el zoom para ver el encuadre.</p><canvas class="canvasEditorFoto" width="300" height="300"></canvas><label>Zoom<input class="zoomEditorFoto" type="range" min="100" max="250" value="100"></label><div class="accionesModalCatalogo"><button type="button" class="cancelarEdicionCatalogo">Cancelar</button><button type="button" class="guardarEdicionCatalogo">Usar este encuadre</button></div></div>`;
                document.body.appendChild(modal); const canvas = modal.querySelector(".canvasEditorFoto"); const ctx = canvas.getContext("2d"); const zoom = modal.querySelector(".zoomEditorFoto"); let desplazamientoX = 0; let desplazamientoY = 0; let inicioX = 0; let inicioY = 0; let moviendo = false;
                function dibujar() { const escalaBase = Math.max(300 / imagen.width, 300 / imagen.height) * (Number(zoom.value) / 100); const ancho = imagen.width * escalaBase; const alto = imagen.height * escalaBase; const x = (300 - ancho) / 2 + desplazamientoX; const y = (300 - alto) / 2 + desplazamientoY; ctx.clearRect(0, 0, 300, 300); ctx.fillStyle = "#111827"; ctx.fillRect(0, 0, 300, 300); ctx.drawImage(imagen, x, y, ancho, alto); }
                dibujar(); zoom.oninput = dibujar; canvas.onpointerdown = event => { moviendo = true; inicioX = event.clientX - desplazamientoX; inicioY = event.clientY - desplazamientoY; canvas.setPointerCapture(event.pointerId); }; canvas.onpointermove = event => { if (!moviendo) return; desplazamientoX = event.clientX - inicioX; desplazamientoY = event.clientY - inicioY; dibujar(); }; canvas.onpointerup = () => { moviendo = false; }; canvas.onpointercancel = () => { moviendo = false; };
                const cerrar = () => modal.remove(); modal.querySelector(".cerrarModalCatalogo").onclick = cerrar; modal.querySelector(".cancelarEdicionCatalogo").onclick = cerrar; modal.querySelector(".guardarEdicionCatalogo").onclick = () => { alGuardar(canvas.toDataURL("image/jpeg", .82)); cerrar(); };
            }; imagen.onerror = () => { modal.remove(); }; imagen.src = String(lector.result || "");
        }; lector.readAsDataURL(archivo);
    }
    function editarProductoCatalogo(producto) {
        const modal = document.createElement("div"); modal.className = "modalCatalogo"; let fotoNueva = producto.imagen || "";
        modal.innerHTML = `<div class="modalCatalogoContenido"><div class="modalCatalogoTitulo"><strong>Editar producto</strong><button type="button" class="cerrarModalCatalogo">×</button></div><p class="subtitulo"></p><label>Precio<input class="precioCatalogoEdicion" type="number" min="0" step="0.01"></label><label>Foto del producto<input class="fotoCatalogoEdicion" type="file" accept="image/*"></label><p class="estadoFotoCatalogo"></p><div class="accionesModalCatalogo"><button type="button" class="cancelarEdicionCatalogo">Cancelar</button><button type="button" class="guardarEdicionCatalogo">Guardar</button></div></div>`;
        document.body.appendChild(modal); const texto = modal.querySelector(".subtitulo"); texto.textContent = producto.nombre + " · " + producto.marca; modal.querySelector(".precioCatalogoEdicion").value = Number(producto.precio) || 0;
        const cerrar = () => modal.remove(); modal.querySelector(".cerrarModalCatalogo").onclick = cerrar; modal.querySelector(".cancelarEdicionCatalogo").onclick = cerrar;
        modal.querySelector(".fotoCatalogoEdicion").onchange = event => { const archivo = event.target.files && event.target.files[0]; if (!archivo) return; abrirEditorFoto(archivo, resultado => { fotoNueva = resultado; texto.textContent = "Foto encuadrada y lista para guardar"; }); };
        modal.querySelector(".guardarEdicionCatalogo").onclick = event => { event.preventDefault(); const productos = obtenerProductos(); const original = (productos[producto.marca] || []).find(p => p.nombre === producto.nombre); if (!original) return cerrar(); original.precio = Math.max(0, Number(modal.querySelector(".precioCatalogoEdicion").value) || 0); original.imagen = fotoNueva; const boton = event.currentTarget; boton.disabled = true; boton.textContent = "Guardando..."; const guardado = guardarProductos(productos); if (!guardado) { boton.disabled = false; boton.textContent = "Guardar"; texto.textContent = "No se pudo guardar. Revisá el almacenamiento."; return; } cerrar(); renderizar(); };
    }
    function renderizar() { const grilla = document.getElementById("grillaCatalogo"); const filtro = document.getElementById("filtroMarcaCatalogo"); if (!grilla || !filtro) return; const lista = datos(); const marcaActual = filtro.value; const marcas = [...new Set(lista.map(p => p.marca))].sort((a,b) => a.localeCompare(b,"es")); filtro.innerHTML = '<option value="todas">Todas las marcas</option>' + marcas.map(m => `<option value="${m.replace(/"/g,"&quot;")}">${m}</option>`).join(""); filtro.value = marcas.includes(marcaActual) ? marcaActual : "todas"; const texto = (document.getElementById("buscarCatalogo")?.value || "").toLocaleLowerCase("es"); const visibles = lista.filter(p => (filtro.value === "todas" || p.marca === filtro.value) && (p.nombre + " " + p.marca).toLocaleLowerCase("es").includes(texto)); grilla.innerHTML = ""; visibles.forEach(p => { const card = document.createElement("article"); card.className = "itemCatalogo"; const imagen = p.imagen || p.foto || p.image || ""; card.innerHTML = `<div class="fotoCatalogo">${imagen ? `<img alt="">` : `<span>${p.nombre.trim().slice(0,1).toUpperCase()}</span>`}</div><small></small><strong></strong><b></b><button type="button" class="btnCatalogoPedido">＋ Agregar al pedido</button><button type="button" class="btnCatalogoEditar">✎ Editar precio o foto</button>`; if (imagen) { const img = card.querySelector("img"); img.src = imagen; img.alt = p.nombre; } card.querySelector("small").textContent = p.marca; card.querySelector("strong").textContent = p.nombre; card.querySelector("b").textContent = p.precio ? "$ " + p.precio : "Precio no cargado"; card.querySelector(".btnCatalogoPedido").onclick = () => { localStorage.setItem("vendefrio_producto_catalogo_pendiente", JSON.stringify({ marca: p.marca, producto: p.nombre })); mostrarPantalla("pedido"); }; card.querySelector(".btnCatalogoEditar").onclick = () => editarProductoCatalogo(p); grilla.appendChild(card); }); if (!visibles.length) grilla.innerHTML = '<p class="catalogoVacio">No se encontraron productos.</p>'; }
    function abrir() { const s = crear(); document.querySelectorAll('body > section[id^="pantalla"]').forEach(item => item.classList.add("oculto")); s.classList.remove("oculto"); renderizar(); }
    window.abrirCatalogo = abrir;
}());
